language: node_js
node_js:
  - stable
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
cache: yarn
script:
  - yarn lint
  - yarn test
  - yarn build --release
before_deploy:
  - cd build
deploy:
  provider: heroku
  app: vuestarterkit
  on:
    repo: kou64yama/vue-starter-kit
    branch: vuestarterkit.herokuapp.com
  api_key:
    secure: KT1f5mi986rnm2gFp8If4o0roxAa7qHDdT5OdyGa4NU24/EqTc4DG6n++8NDq2XeemyM+vdmnzTTlpXjdUPODGsNosmV7HfzA9ZFC6soCzdmsNqzvh8FvDW7J6OKQDg0K5FAB+5uZYW3+11SBP6fmNZ5RKApJ+syDLvslJIyakUJXjbZ9jSTiQhk4JbX4O2NOw8/e49U5p0tNXYAIAb6wHh8SaFauhHF0uzJVofClQXVUe+3u/AVsbFCD1THsfIFM/Z8OsC5g1aAncpO+uiaQjHaYQWO4i8l0RTw6x/ZA53BPx/pLr29GaElT9lJSTlWxdg38i2UGpYPt0TXM5zDH58Zr8tOtTJoBubxvfwZ/J+3Z1FYvYe5kE3sItxlbv5ak4JivRMWp6m7sVpg91ujgvezEn/QKVhxgRHWzIL7C+7vpNFTmK4XCFtiGtZN52CmKXHggKLftwYdk/CVloPKTpajg3/y1wi5441mj+ZBWzx93j2Mvl5tA7M0i0HhQ7Nxmj0+5jxdKACUc3RCIIfqLntOYAPYLAkv11O0UYI/YSNkaj6JS+AkiSsM+lmhN9qn3hZorkCovV20mPvIlfjqzUtV6M+p3M3St/uNhGThgsEt42Emwwo/ouTulR1u5IiLKmB1Hcbea3R2jMshqkFRXOC7M2U+ZofaHrx3YUYOgBs=
  skip_cleanup: true
